### ISSUE TITLE
InputFunctionException in line 242 of .../CHIPS/chips.snakefile

### ISSUE THREAD

**Issue by mdozmorov** [liulab-dfci/CHIPS#1]
Hi. I'm trying CHIPS on single-end ATAC-seq data, and got the following error:
````
(chips) -bash-4.1$ snakemake -np  -s CHIPS/chips.snakefile --rerun-incomplete
fastp 0.20.1
/home/../miniconda3/envs/chips/lib/python3.6/site-packages/snakemake/workflow.py:743: DtypeWarning: Columns (1,2,7) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(compile(code, snakefile, "exec"), self.globals)
Gapdh found in bed
Actb found in bed
Trp53 found in bed
Homer module is being used and details file was copied.
Homer module is being run.
Building DAG of jobs...
InputFunctionException in line 242 of /home/sequencing/ATAC_seq/CHIPS/chips.snakefile:
KeyError: 'S1_S1_R1_001.fastq.gz'
Wildcards:
````
I'm rather new to Snakemake, so not sure what to do about it. The filenames look correct in `config.yaml.`, and it is not the first file the error is thrown.

Thanks,
Mikhail

**Comment by mdozmorov** [comment]
A couple of previous errors that I was able to fix.
````
(chips) -bash-4.1$ snakemake -np  -s CHIPS/chips.snakefile --rerun-incomplete
FileNotFoundError in line 72 of /home/sequencing/ATAC_seq/CHIPS/chips.snakefile:
[Errno 2] No such file or directory: 'cidc_chips/ref.yaml'
````
This is caused by line 3 in `config.yaml`. The hard-coded `cidc_chips` should be removed, because the `ref.yaml` is in the project directory.

The other error was similar:
````
(chips) -bash-4.1$ snakemake -np  -s CHIPS/chips.snakefile --rerun-incomplete
fastp 0.20.1
FileNotFoundError in line 81 of /home/sequencing/ATAC_seq/CHIPS/modules/new_report.snakefile:
[Errno 2] No such file or directory: 'cidc_chips/report/ref_assembly.csv'
````
So, I changed `cidc_chips` to `CHIPS`. Then, the reported error occurred.

**Comment by liulab-dfci** [comment]
Hi Mihail, can you please try the most recent version in this repo? I moved the repo from bitbucket to github and there are some bugs need to be fixed (e.g, cidd_chips). ---Tommy

**Comment by crazyhottommy** [comment]
Hi Mikhail, now the paper is on F1000 https://f1000research.com/articles/10-517/v1 there are examples there, may be helpful for you.

**Comment by mdozmorov** [comment]
Congratulations, Ming, for publishing it, and thank you for sharing! I trust this issue is fixed, will close. CHIPS is still on my list, waiting for new data. Closer to the top is MAESTRO, we are getting some scRNA and scATAC-seq.

**Comment by crazyhottommy** [comment]
Thanks! sounds good. let us know anything we can help with!
